
## 监控配置
management:
  context-path: /sys-app
  security:
    enabled: false
spring:
  application:
    name: arukas
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/arukas
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console


